name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test C#
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code
    - name: Build C# Code
    - run: dotnet build
    - name: test C#
    - run: dotnet test
    name: Build and test TypeScript
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies and build typescript
    - working-directory: cd ./DotnetTemplate.Web
    - run: |
            npm install
            npm run build
    - name: test TypeScript
    - working-directory: cd ./DotnetTemplate.Web
    - run: |
            npm t
            npm run lint